# Generated by Django 6.0.6 on 2026-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'dietary'}, related_name='profiles', to='recipes.tag'),
        ),
    ]
