# Generated by Django 6.0.6 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='breakfast_pct',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='dinner_pct',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='lunch_pct',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='snack_pct',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='target_carbs_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='target_fat_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='target_protein_g',
            field=models.FloatField(default=0),
        ),
    ]
